import Head from 'next/head';
import AppBar from '@component/components/AppBar/AppBar';
import FirstPart from '@component/components/FirstPart/FirstPart';
import { Box, useMediaQuery } from '@mui/material';
import SecondPart from '@component/components/SecondPart/SecondPart';
import ThirdPart from '@component/components/ThirdPart/Thirdpart';
import FourthPart from '@component/components/FourthPart/FourthPart';
import FifthPart from '@component/components/FifthPart/FifthPart';

export default function Home() {
  // const innerWidth = window.innerWidth;
  const isClient = typeof window === 'object';

  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/kirapratik-logo.svg" />
      </Head>
      {isClient && useMediaQuery('(max-width:600px)') ? '' : <AppBar></AppBar>}

      <Box
        sx={{
          color: '#fff',
          // marginTop: { xs: '4rem', sm: '7rem', md: '5rem' },
        }}
      >
        <FirstPart></FirstPart>
        <SecondPart></SecondPart>
        <ThirdPart></ThirdPart>
        <FourthPart></FourthPart>
        <FifthPart></FifthPart>
      </Box>
    </div>
  );
}
